/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplicity;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        // Game.startGame();
    }
}
