/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simplicity;

public class App {

    public static void main(String[] args) {
        System.out.println("Welcome to Sim-Plicity");
        Game.startGame();
    }
}
